services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gitpack
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --chdir /code/gitpack gitpack.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db