services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gitpack
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    
  web:
    build:
      context: ./gitpack
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 --chdir /code gitpack.wsgi:application
    volumes:
      - ./gitpack:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend/.env.local
    command: npm run dev
    depends_on:
      - web