databases:
- name: gitpackdb
  databaseName: gitpack
  user: gitpack
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"

services:
  - type: web
    plan: free
    name: gitpack
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn --chdir gitpack gitpack.wsgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gitpackdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4