databases:
  - name: gitpackdb
    plan: free
    databaseName: gitpack
    user: gitpack

services:
  - type: web
    plan: free
    name: gitpack
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn --chdir /code/gitpack gitpack.wsgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gitpackdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4